name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: dkssud8150/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 63a70d019168a6fa64524a889204ee0a
          TIMEZONE: Asia/Seoul
